apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-staging
  namespace: default
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: daniel@hawton.org
    privateKeySecretRef:
      name: letsencrypt-cluster-staging
    http01: {}
